moonwards1/Moonwards-Virtual-Moon

core/autoload/gamestate.gd
Fixed:
- log_all_signals_print_x type casting errors -> it's best not to specify argument type here and function will handle anything in correct manner.
- Error calling method from signal 'log_gamestate' -> previous signal name is 'gslog', so now it should be 'gamestate_log'. Sometimes signal is referenced as 'log_gamestate' so it's causing confusion. All calls unified to `gamestate_log`.
=> Issue #103: Functions errors on gamestate.gd

Interface/Hud/Chat/Chat.gd, Interface/Hud/Chat/Chat.tscn, Interface/Hud/Chat/ChatInput.gd, assets/Player/avatar_v2/scripts/Player.gd
The player no longer responds to input meant for Chat.
The only thing modified in Player.gd is one set_process_input being changed to set_process_unhandled_input and the _input method being changed to unhandled_input.
=> Chat now handles input.

assets/AudioTour/AudioSphere.gd, assets/AudioTour/AudioSphere.tscn, sounds/ding7.ogg
Specify which file to use as the audio by clicking on the Audio File
property in the Inspector tab when the AudioTour node is highlighted in the tree.
=> Audio tour node made. Plays OGG files.

Interface/Hud/Chat/Chat.gd, Interface/Hud/Chat/Chat.tscn
Chat can now be toggled on and off by the player. 
Other events can tell Chat to disappear by calling get_tree().call_group( "Chat", "hide_chat" )
Some UX improvements could be made in regard to how the player can manually toggle the visibility of the chat. It needs to be animated and given a notification thing for the player to know that a message has been sent while visibility toggled.
=> Chat improvements.

Utilities/AudioTour/AudioSphere.tscn
The AudioSphere did not have it's signal connected properly for some
reason. This commit fixes that. Now when the player interacts with the
AudioSphere it will actually play the audio.
It basically fixes a minor oversight that prevented AudioSphere from working right.
=> Connect interacted_with to play_sound.

Utilities/AudioTour/AudioSphere.gd, Utilities/AudioTour/AudioSphere.tscn
I created a group that manages all audio players that are meant to have
only one playing at a time. Intended method of using these is to do
get_tree().call_group( "SoloAudioPlayer", "stop" ).
=> Made and placed in group SoloAudioPlayer.

Utilities/AudioTour/AudioSphere.tscn, Worlds/MoonTown/Constructs/Moon_Town_Master/Moon_Town_Master.tscn
This commit removes the ImmediateGeometry from AudioSphere and creates a
new AudioSphere that plays the AudioTour Introduction.
=> Remove AudioSphere model and add intro AudioSphere

LegacyPlayer/avatar_v2/interactor/Interactor.gd
Previously Interactor.gd was hiding the InteractDisplay whenever
the Interact did not detect collisions. Now Interactor only hides
InteractDisplay when it first stops colliding with an interactable.
=> Fix bug where Interactor was hiding InteractDisplay when not colliding with anything.

SceneComponent/Utilities/AudioTour/AudioSphere.gd, SceneComponent/Utilities/AudioTour/AudioSphere.tscn, Script/Manager/SignalsManager/AudioSignals.gd, Script/Manager/SignalsManager/SignalsManager.gd
- AudioSphere abides by Godot code guidelines.
- AudioSphere has more logical way of stopping other solo audio players.
- Follows code style guidelines.
- AudioSphere enforces audio files be present.
Resolves issue #321
=> AudioSphere uses Signals manager

Tree/Interface/MainMenu/MainMenu.tscn
- Main Menu theme now in line with concept art
- Added gfx to main menu buttons.
- Main Menu emits signal when start game is pressed.
- Script made for button gfx to adhere to SRP.
- Add improved Moonwards logo to project.
- Focus neighbors now navigable.
- Add updated logo in svg and png.
- Grey out MainMenu buttons.
Addresses issue #268
=> Add overhauled menus

Tree/Interface/Hud/Chat/Chat.gd
When you press the V key, the chat history will still remain visible.
Resolves issue: #359
=> Lower chat keeps chat history visible

SceneComponent/Actor/InteractorComponent.gd, Script/GameLogic/Interact/Interactor/Interactor.gd, Script/Manager/SignalsManager/HudSignals.gd, Tree/Interface/Hud/InteractDisplay/InteractDisplay.gd, project.godot
This PR is intended to make stair climbing Interactables feel more natural to use. 
When completed, it will display to the player what is the closest Interactable.
This adds the action "interact_with_closest" and uses the keyboard key F
"toggle_fly" action has been changed to use the M key.
resolves #462
=> Interactor can interact with closest interactable

SceneComponent/Interface/Hud/CrosshairRayCast.gd, SceneComponent/Interface/Hud/HudCrosshair.gd, Script/Manager/Helpers.gd, Script/Manager/SignalsManager/MenuSignals.gd
I added the signal that HudCrosshair listens for in MenuSignals. My reasoning was that menus, like the new uis, would need it too. I can move it to HudSignals if need be.
resolves #545
=> HudCrosshair hides itself when mouse is active

Assets/MoonTown/Models/Neighborhood/Neighborhood-1.tscn
Changing the location of the DVT collision shape for Airlock Bay in the entrance to First Gallery Upper, and adding a collision shape for the DVT of FGU in that entrance should resolve a small handful of LOD level display issues.
What it fixes will be confirmed before merge of the PR is requested.
=> Correct LOD display levels during movements between Airlock Bay and First Gallery Upper

Assets/MoonTown/Models/Neighborhood/Neighborhood-1.tscn
This involved the LOD0 list for the node called `Reversing-Visibility-Trigger` of `First_Gallery_Upper`
=> Add Neighborhood scenes to LOD0 lists of FGU's RVT

Assets/MoonTown/Constructs/First_Atrium/First_Atrium.glb, Assets/MoonTown/Constructs/First_Atrium/First_Atrium.tscn
Stairs that weren't navigable have been replaced so that all the stairs in First Atrium now work and everything in it is accessible. (Though there are a few glitchy spots that can  be refined at some later date.)
=> Improved stairs in First Atrium

Assets/MoonTown/Constructs/Center_Atrium/Center_Atrium.tscn
The two new tooltips are both near this point: 
x: 25.5 y: 66.4, z: -105.7
The previous one has had its text edited. It is accessible by climbing 5 stories from the location of the other tooltips and going to the window on the other side of the columns, or going here: 
x: -8.2 y: 83,2 z: -107.2
=> Complete Center Atrium tooltips

Assets/MoonTown/Constructs/Airlock_Bay/Airlock_Bay.tscn
There's only the one tooltip for the airlock bay. It's at the end of the tunnel on the big airlock, x: 124.5  y: 99.6  z: -207.3
=> Add Garage Airlock tooltip

Assets/MoonTown/Constructs/Rec_Hab_1/Rec_Hab_1.glb, Assets/MoonTown/Constructs/Rec_Hab_1/Rec_Hab_1.tscn, Assets/MoonTown/Constructs/Rec_Hab_1/Water_001.material
This removed a utility texture used for UV work in Blender from the pool water material for the LOD1 and LOD2 version of RecHab1.
This time it's been checked in game and everything is fine. 
Ready for merge.
=> Change material on pool water of LOD1 and LOD2 of RecHab1

Assets/SharedAssets/Textures/ImageTextures/Intro-Slide-6.jpg, Assets/SharedAssets/Textures/ImageTextures/Intro-Slide-6.jpg.import, Tree/World/Moon_Town_Main.tscn
A new image has been added to the SharedAssets / Textures / ImageTextures folder, Intro-Slide-6, and that image is now part of the welcome-presentation node of First_Gallery_Upper, which is an instance of Billboard.tscn
These images take a long time to set up, and so I'm now doing them one at a time, as time seems available.
So, this can be merged. I'll make a new PR once I have another image to add.
=> Add Intro-Slide-6 to welcome-presentation in First Gallery Upper

SceneComponent/Actor/InteractorComponent.gd, SceneComponent/Interface/Hud/Chat/Chat.tscn, SceneComponent/Interface/Hud/InteractDisplay/InteractDisplay.tscn, SceneComponent/Interface/Hud/InteractsMenu.gd
I went ahead and made InteractorComponent respect chat being active as well.
We really ought to figure out a way for Chat to stop everything without everything having to specifically listen for it.
resolves #664
=> Chat stops Interactors #664

SceneComponent/Object/Airlock/Airlock.tscn, SceneComponent/Object/Airlock/AirlockDoorInteractable.gd, SceneComponent/Object/Airlock/AirlockManager.gd
QA checks: 
Test that airlocks openings are networked and that the simulation is played for everyone. Passed.
Test that client will have airlock synced even when the airlock is animating for other players. Probably passed. Might need more testing.
resolves #707
=> Simulate Airlock #707

SceneComponent/Actor/AI/MwAI.gd, Script/Network/NetworkManager/ANetworkInstance.gd, addons/joyeux_npc_editor/src/Core/Control_Components/BehaviorNode.gd, addons/joyeux_npc_editor/src/Core/Control_Components/FileSeparator.gd, addons/joyeux_npc_editor/src/Core/Control_Components/SeparatedLabel.gd, addons/joyeux_npc_editor/src/Core/Nodes.gd, addons/joyeux_npc_editor/src/interface/behaviors/scenes/Behaviour_tree_editor.gd
Fixes an issue that duplicates the resources cached by the NPC editor and changes the way it stores them so they are freed upon exit, also avoids duplication of NetworkInstance.
There are 22 orphans to be removed before merging
=> Memory leak and orphaned nodes fix

SceneComponent/Actor/Vehicle/AthleteRover/RoverRideInteractable.gd
Other vehicles cannot take control of the Rover. This prevents the bugs that happen when mounting a Rover from a Rover.
resolves #719
=> Vehicles cannot take control of the Rover #719

SceneComponent/Audio/AudioSphere/AudioSphere.tscn
I didn't create the issue, but while working on #814 I found out interacting with the audospeheres was hard due to their small collision shape and their position, making you able to interact with it only being inside it
=> Make AudioSphere's collisions bigger so they are easier to interact with

project.godot
Add basic joypad support. You still need a mouse to look around.
More so as a workaround for certain OSes having input issues.
=> Add joypad controls to Moonwards

SceneComponent/Object/Airlock/AirlockDoorInteractable.gd, project.godot
A very hacky workaround for Godot behaving differently for exported instanced. 
It still fails to connect occasionally. But this will work well enough for the current alpha until we can get 0.2.1
=> Fix Airlock and initial connection issues mostly
