moonwards1/Moonwards-Virtual-Moon

_tests/slides/TestScreens.tscn, assets/Player/avatar_v1/player.tscn, assets/Player/avatar_v2/player.tscn, assets/Slides/BucknellRocket/BucknellRocketSlides.tscn, assets/Slides/Lunar Machines/Regolith.tscn, assets/Slides/Lunar Machines/Slide 2nd approach.tscn, assets/Slides/Lunar Machines/Slide0.tscn, assets/Slides/Lunar Machines/Slide1.tscn, assets/Slides/Lunar Machines/Slide2.tscn, assets/Slides/Lunar Machines/Slide3.tscn, assets/Slides/ScreenViewer.tscn, scenes/FirstGalleryUpper.tscn
Godot is a business of redesigning every scene I have preview. Other than that fixed the test and added simple / example screen next to a rocket.
=> Set up animation of Bucknell rocket

UserInterface.gd, assets/UI/Menu/Updating_UI.gd, scripts/MainMenu.gd
First pull request done by me, hooray!
=> Options path fixed

Main.tscn, _tests/scene_mp/multiplayer_test_scene.tscn, core/autoload/gamestate.gd
=> resolve some issues

assets/UI/Options/Settings.gd, assets/UI/Options/Settings.tscn, core/autoload/autoload-options.gd, project.godot
Works upon #61 and closes  #45
=> Resolution fix

project.godot
A small fix for the recently renamed autoload.
=> Options autoload fix

_tests/Terrain/Lalande_splatmap.shader, _tests/Terrain/terrain.shader, _tests/Terrain/terrain.tres
For performance disable detail and/or double filter
Enable both for the full shader
=> Stochastic shader saved at _tests

assets/UI/Options/Options.gd, core/autoload/autoload-options.gd, core/autoload/debug.gd, core/autoload/input_maping.gd, scripts/UserSettings.gd
This also fixes an issue on linux where the game wouldn't load the json files.
=> Unify all settings in the same file and format. 

core/autoload/debug.gd
File was part of the last PR, but got somehow unstaged. Closes #136
=> Fixes debug.gd crash

cloudbuild.yaml
Cloud build file for game server
=> Issue #111: New game server

Interface/MainMenu/Lobby/Lobby.gd, addons/HuePicker/HuePicker.gd, assets/Player/avatar_v2/scripts/Player.gd, core/autoload/GameState.gd, core/autoload/Options.gd, utility/GlobalLogger.gd
Not ready yet, PR open for discussion and tracking issues
=> Network Fix

Interface/PauseMenu/PauseMenu.gd
Only modifies PauseMenu.gd. Super simple.
=> Pause menu no longer tries to start when forbidden.

Themes/ChatDisabledLineEdit.tres, Themes/ChatLineEdit.tres, Themes/ChatMainBGPanel.tres, Themes/ChatPanelRichTextLabel.tres, Themes/ChatTheme.tres
=> Chat given it's own theme.

Themes/MainMenu.tres
This commit only affects Themes/MainMenu.tres. It makes pressing buttons
feel more responsive and intuitive.
=> Button Pressed Style more interactive.

Interface/Hud/Chat/Chat.gd, Interface/Hud/Chat/Chat.tscn
Affects Chat.tscn and Chat.gd. Only adds window toggle functionality.
=> Chat toggles text window.

assets/Interactable/Interactable.gd, assets/Interactable/Interactable.tscn, assets/Player/avatar_v2/player.tscn, assets/Player/interactor/Interactor.gd, assets/Player/interactor/Interactor.tscn
This adds the Interactor node (player uses to interact with) and Interactable node (for objects that the player interacts with. It adds an Interactor as a child of KinemtaticBody in Player.tscn.
A bug fix was necessary for the Interactor to get where the player camera was pointing due to how the NPCs and their cameras function.
=> Interactor and Interactable nodes for the player to interact with the environment.

Interface/Hud/Hud.tscn, Interface/Hud/InteractDisplay/InteractDisplay.gd, Interface/Hud/InteractDisplay/InteractDisplay.tscn, assets/Player/interactor/Interactor.gd
Edits Interaction nodes and creates InteractorDisplay
=> Create a display for interactions.

Boot.gd, export_presets.cfg
Fixes the server initialization:
Manual override is an argument: --server=true
=> manual override for server initialization

Boot.gd, Core/Network/Lobby.gd
Adds network verbose so we can identify the connection issue. 
Changes the server connection from specific IP to wildcard. 
Changes compression mode from default to FASTLZ compression 
Fixes booting from non-connected world to main menu, mouse visibility included
=> Network debug

Utilities/AudioTour/AudioSphere.gd, Utilities/AudioTour/AudioSphere.tscn, Worlds/MoonTown/Constructs/Moon_Town_Master/Moon_Town_Master.tscn
I made a new folder inside Utilities for the AudioSpheres called Audio Tour. 
I added the Audio Spheres to the Audio Markers in moon_town_master with the corresponding audio files. The listing for the audio markers were fixed as well as they were miss ID'ed.
=> Audio tour given AudioSpheres.

Worlds/MoonTown/Constructs/Moon_Town_Master/Moon_Town_Master.tscn
Simple change to the Audio Spheres so they have the correct files to play.
=> AudioSpheres have correct audio file.

Core/Network/Lobby.gd, Core/Options.gd, Core/World/World.gd, Worlds/MoonTown/Constructs/First_Gallery/First_Gallery_Upper.tscn, Worlds/MoonTown/Constructs/Moon_Town_Master/Moon_Town_Master.gd, Worlds/MoonTown/Constructs/Moon_Town_Master/Moon_Town_Master.tscn
New world is now working mostly.
This pull request makes the new world load instead of the LegacyWorld. 
Audio Tour is now functional.
=> World managing refactor

Assets/Interface/ExtraInfoDisplay.tres, Assets/Interface/Fonts/ExtraInfoDisplayTitledjv_bold.tres, Assets/Interface/StyleBoxes/ExtraInfoDisplayBgPanel.tres, Script/Manager/SignalsManager/MenuSignals.gd, Script/Manager/SignalsManager/Signals.gd, Trees/Interface/ExtraInfoDisplay/ExtraInfoDisplay.gd, Trees/Interface/ExtraInfoDisplay/ExtraInfoDisplay.tscn, project.godot
This commit adds ExtraInfoDisplay.tscn and it's associated files. It
adds the class MenuSignals and adds the class to Signals manager. This
commit adds the Action hide_extra_info_display to InputMap and sets it's
input as the 4 on the keyboard.
=> Add Extra Info Display.

Script/Manager/SignalsManager/HudSignals.gd, Script/Manager/SignalsManager/MenuSignals.gd, Script/Manager/SignalsManager/Signals.gd, Trees/Interface/ExtraInfoDisplay/ExtraInfoDisplay.gd
- Remove ExtraInfoDisplay from MenuSignals.
- Add ExtraInfoDisplay to HudSignals.
Addresses this issue: https://github.com/moonwards1/Moonwards-Virtual-Moon/issues/260#issue-602455648
=> Add new HudSignals class to Signals Manager.

Tree/Interface/Hud/Chat/Chat.gd, Tree/Interface/Hud/Chat/Chat.tscn, Tree/Interface/Hud/Hud.gd, Tree/Interface/Hud/Hud.tscn, Tree/Interface/Hud/InteractDisplay/InteractDisplay.gd, Tree/Interface/MainMenu/About/About.tscn, Tree/Interface/MainMenu/MainMenu.gd, Tree/Interface/MainMenu/MainMenu.tscn, Tree/Interface/PauseMenu/PauseMenu.gd, Tree/Interface/PauseMenu/PauseMenu.tscn
Pause and HUD now work when instanced. They are not reliant on being globals.
=> Menus now work as their own instance.

Tree/Interface/Hud/Chat/Chat.gd, Tree/Interface/MainMenu/MainMenu.gd, Tree/Interface/PauseMenu/PauseMenu.gd, Tree/Interface/PauseMenu/PauseMenu.tscn
And remove Pause handling show() calls.
=> Remove legacy code from Menus.

Tree/Interface/MainMenu/MainMenu.gd, Tree/Interface/MainMenu/MainMenu.tscn, Tree/Interface/MainMenu/MainMenuHBox.gd, Tree/Interface/MainMenu/MainMenuTab.gd, Tree/Interface/UserSettings/UserSettings.gd, Tree/Interface/UserSettings/UserSettings.tscn, _tests/NewDemo/TestScene.tscn
- UserSettings now uses signal manager.
- Reformat UserSettings for better room management.
- Updated main menu to GDD requirements.
=> UserSettings updates player data using signals.

Script/Network/GameServer.gd, Tree/World/Moon_Town_Main.tscn, _tests/NewDemo/TestScene.tscn, project.godot
#255
[Add networked features to player logic](https://app.gitkraken.com/glo/board/5e96433deb480d00123f5d87/card/5e9898e6f95f6f0011e7e856)
=> Predefined dynamic spawn points

Script/Manager/Logger.gd, _tests/Manager/LoggerTest.gd, _tests/Manager/LoggerTest.tscn, project.godot
- removed manual file write,
- set up Godot's automated file log,
- refactored the logger.
=> Issue #287: Rewrite the logger

Assets/Interface/Fonts/InteractDisplayFont.tres, Tree/Interface/Hud/InteractDisplay/InteractDisplay.tscn
- Add a font to make Interact Display more legible.
Resolves issue #265
=> Anchor points are setup for Interact Display

Script/Manager/ResourceManager/ResourceThreadedLoader.gd, Script/Manager/SceneManager/SceneManager.gd, Script/Manager/SignalsManager/ResourceSignals.gd, Script/Manager/SignalsManager/SignalsManager.gd, Script/Network/GameClient.gd, Script/Network/GameServer.gd, Script/Network/NetworkManager/ANetworkInstance.gd, Tree/Interface/Hud/LoadingScreen/LoadingScreen.gd, Tree/Interface/Hud/LoadingScreen/LoadingScreen.tscn, project.godot
[Create a scene manager to handle loading & context management](https://app.gitkraken.com/glo/card/2ed703729bb549ad955a58b791c37d22)
=> Add threaded resource loader

Assets/Interface/ChatTheme.tres, Assets/Interface/Fonts/ChatFont.tres, SceneComponent/Interface/Hud/ChatComponent.gd, Tree/Interface/Hud/Chat/Chat.gd, Tree/Interface/Hud/Chat/Chat.tscn, Tree/Interface/Hud/Chat/ChatDisplay.gd
- Make Chat resizeable.
- Chat messages disappear if there are too many.
- Urls work in Chat.
- Shouting and whispering is doable. (But does not affect range yet)
- Add help context for Chat.
- Add/improve Chat keyboard functions.
Resolves issue #354
=> Improve functionality of Chat

SceneComponent/Actor/PlayerInteractor.gd, SceneComponent/Utilities/Interactable/Interactable.tscn, SceneComponent/Utilities/Interactor/Interactor.tscn, Tree/Actor/Player/FemalePlayer.tscn
Makes Interactor and Interactables work with the project.
Give the Player scene an Interactor.
Resolves issue #361
=> Player interactor

Tree/Actor/Player/FemalePlayer.tscn
Adds the Chat to the player scene.
=> Add Chat to Player scene.

SceneComponent/Actor/InputController.gd, Script/Manager/SignalsManager/HudSignals.gd, Tree/Actor/Player/HumanPlayer.tscn, Tree/Interface/Hud/Chat/Chat.gd, Tree/Interface/Hud/Chat/Chat.tscn, Tree/Interface/Hud/Chat/ChatInput.gd, Tree/World/Moon_Town_Main.tscn, project.godot
Resolves issue #358 
Thanks Karim for helping me figure out what the problem was.
=> Player scene ignores chat typing input.

Tree/Interface/Hud/Chat/Chat.gd, Tree/Interface/Hud/Chat/ChatInput.gd, project.godot
=> Chat listens for actions meant for it

project.godot
=> Name 3D physics layers

Assets/Interface/StyleBoxes/InteractDisplayBackground.tres, SceneComponent/Actor/PlayerInteractor.gd, SceneComponent/Interface/PlayerHud.tscn, Script/Manager/SignalsManager/HudSignals.gd, Tree/Interface/Hud/InteractDisplay/InteractDisplay.gd, Tree/Interface/Hud/InteractDisplay/InteractDisplay.tscn, Tree/World/Moon_Town_Main.tscn
=> Interact Display now works with new project. Enhance visibility.

SceneComponent/Actor/AnimationController.gd, SceneComponent/Actor/HumanoidMovement.gd, SceneComponent/Actor/HumanoidMovement.tscn, _tests/NewDemo/MovementTesting.tscn
[Player moves without any contol active](https://app.gitkraken.com/glo/board/5e96433deb480d00123f5d87/card/5ed67cca17c3960011ebe2f4)
=> Improved character control.

Script/GameLogic/Interact/Interactable/Interactable.gd, Script/GameLogic/Interact/Interactor/Interactor.gd
=> Interactable sets it's collision layer automatically

Assets/Interface/Fonts/InteractsMenuButtons.tres, Assets/Interface/Fonts/InteractsMenuDescription.tres, Assets/Interface/InteractsMenu.tres, Assets/Interface/StyleBoxes/InteractsMenuDescriptionPanel.tres, Assets/Interface/StyleBoxes/InteractsMenuPanel.tres, SceneComponent/Actor/InteractorComponent.gd, SceneComponent/Actor/InteractorComponent.tscn, SceneComponent/Interface/Hud/InteractsMenu.gd, SceneComponent/Interface/Hud/InteractsMenu.tscn, SceneComponent/Interface/PlayerHud.tscn, Script/GameLogic/Interact/Interactor/Interactor.gd, Script/Manager/SignalsManager/HudSignals.gd
=> Add interactable objects selection menu

SceneComponent/Actor/InteractorComponent.gd, SceneComponent/Actor/InteractorComponent.tscn, SceneComponent/Interface/Hud/InteractsMenu.gd, Script/GameLogic/Interact/Interactable/Interactable.gd, Script/GameLogic/Interact/Interactor/Interactor.gd, Script/Manager/Helpers.gd, Script/Manager/SignalsManager/HudSignals.gd
=> Overhaul InteractsMenu.

SceneComponent/Interface/Hud/InteractsMenu.gd
Just a hotfix of InteractsMenu bugs.
resolves #413
=> Fix some InteractsMenu bugs

SceneComponent/Actor/InteractorComponent.gd, SceneComponent/Actor/InteractorComponent.tscn, SceneComponent/Actor/Vehicle/AthleteRover/RoverRideInteractable.gd, SceneComponent/Audio/AudioSphere/AudioSphere.tscn, SceneComponent/Interface/Hud/InteractsMenu.gd, Script/Component/Core/AComponent.gd, Script/GameLogic/Interact/Interactable/Interactable.gd, Script/GameLogic/Interact/Interactor/Interactor.gd, Script/Manager/SceneManager/SceneManager.gd, Script/Manager/SignalsManager/HudSignals.gd, Script/Network/NetworkManager/ANetworkInstance.gd
My first PR for Moonwards Networking!
resolves #418
=> Add networked functionality to interactors

SceneComponent/Actor/InteractorComponent.gd, SceneComponent/Actor/InteractorComponent.tscn, SceneComponent/Actor/Vehicle/AthleteRover/RoverMovement.tscn, SceneComponent/Actor/Vehicle/AthleteRover/RoverRideInteractable.gd, SceneComponent/Interface/Hud/InteractsMenu.gd, Script/Manager/SignalsManager/HudSignals.gd, Tree/Actor/Player/HumanPlayer.tscn, Tree/Actor/Vehicle/AthleteRover/AthleteRover.tscn
Works similarly to how Control nodes grab focus. 
resolves #429 and resolves #435
=> Interactor Menu focuses on one InteractorComponent at a time.

SceneComponent/Actor/InteractorComponent.gd, SceneComponent/Actor/Vehicle/AthleteRover/RoverRideInteractable.gd, SceneComponent/Interface/Hud/InteractsMenu.gd, Script/GameLogic/Interact/Interactable/Interactable.gd
Should I remove the commented out code for InteractorComponent history rollback in InteractsMenu?
resolves #441  resolves #438
=> Fix notorious InteractsMenu bugs

SceneComponent/Interface/PlayerHud.gd, SceneComponent/Interface/PlayerHud.tscn, Script/Manager/HudManager/HudManager.gd, Script/Manager/SignalsManager/HudSignals.gd, project.godot
Create a global that manages the PlayerHud in game. 
resolves #431
=> Hud takes visibility requests

SceneComponent/Audio/AudioSphere/AudioSphere.gd, SceneComponent/Audio/AudioSphere/AudioSphere.tscn, SceneComponent/Audio/AudioSphere/AudioSphereAnimations.gd
Makes AudioSpheres animate for interactions again.
resolves #452
=> Simple fix for AudioSphere animations

Assets/MoonTown/Constructs/Moon_Town_Master/Moon_Town_Master.tscn
=> Add titles and description to Audio Tour AudioSpheres

SceneComponent/Interface/Hud/InteractsMenu.gd
=> Fix InteractsMenu crash when starting inside Interactables

SceneComponent/Actor/CameraController.gd, SceneComponent/Actor/Vehicle/AthleteRover/RoverRideInteractable.gd, Script/Component/Core/AComponent.gd, Script/Entity/Core/AEntity.gd, Script/Network/GameClient.gd, Script/Network/GameServer.gd, Script/Network/NetworkManager/ANetworkInstance.gd
* Refactored the way the instance owners' peer id can be fetched
* Refactored enabling entities & components to allow accounting for peer ownership
* Adjusted Athlete Rover and AComponent accordingly.
Resolves #475
=> Fix network ownership issues #475

SceneComponent/Actor/InteractorComponent.gd, SceneComponent/Actor/InteractorComponent.tscn, SceneComponent/Interface/Hud/InteractsMenu.gd, Tree/Actor/Player/HumanPlayer.tscn, Tree/Actor/Vehicle/AthleteRover/AthleteRover.tscn
=> Fix interactor crash #477

Script/GameLogic/Interact/Interactable/Interactable.gd
=> Add Interactable activation API

Assets/Interface/Fonts/LoggerConsoleFont.tres, Assets/Interface/LoggerConsoleTheme.tres, SceneComponent/Interface/LoggerConsole/FontSize.gd, SceneComponent/Interface/LoggerConsole/LoggerConsole.tscn, SceneComponent/Interface/LoggerConsole/LoggerText.gd
I made it where the Logger prints out different color text for each message type and it alternates color brightness.
Ready to be merged.
resolves #426
=> Add alternating color to log lines

Assets/MoonTown/Models/Human_Model/FemalePlayerModel.tscn, Assets/MoonTown/Models/Human_Model/PlayerModel.tscn, SceneComponent/Actor/Humanoid/AnimationController.gd, SceneComponent/Actor/Humanoid/AnimationController.tscn, SceneComponent/Actor/Humanoid/HumanoidMovement.gd
Do not merge until I give the okay, please.
resolves #449
=> Fix Vertical Stairs feel

SceneComponent/Actor/CameraController.gd, SceneComponent/Actor/Humanoid/HumanoidInput.gd, SceneComponent/Actor/Humanoid/HumanoidMovement.gd, SceneComponent/Interface/Hud/FlightSpeedDisplay.gd, SceneComponent/Interface/Hud/FlightSpeedDisplay.tscn, SceneComponent/Interface/PlayerHud.tscn, Script/Entity/ActorEntity.gd, Script/Entity/ActorEntityState.gd, Script/Manager/SignalsManager/EntitySignals.gd, Script/Manager/SignalsManager/HudSignals.gd, Tree/Interface/Hud/Chat/Chat.tscn, project.godot
=> Feat/add flight mode #480

SceneComponent/Interface/Hud/InteractsMenu.gd
This commit does not remove the workaround in InteractorComponents grab/lose_focus funcs.
resolves #486
=> InteractsMenu cleanly switches Interactors

SceneComponent/Actor/Vehicle/AthleteRover/RoverRideInteractable.gd, SceneComponent/World/DynamicLoading/DynamicVisibilityTrigger.gd, SceneComponent/World/DynamicLoading/ReversingVisibilityTrigger.gd, Script/ExtensionClass/LodModel.gd, Script/Manager/VisualTriggerManager/VisibilityManager.gd, Script/Manager/VisualTriggerManager/VisibilityManager.tscn, project.godot
Resolves #498 
This also aims to resolve #482
=> Add visibility trigger management

SceneComponent/Display/ViewportViewer.gd
This related to #509
Resolves #511
=> Fix monument not working in MoonTown (#511)

SceneComponent/Display/MakersMonument/MonumentContent.gd, SceneComponent/Display/MakersMonument/MonumentContent.tscn, SceneComponent/Display/ViewportViewer.gd, SceneComponent/Display/ViewportViewer.tscn
This PR fixes ViewportViewer misalignment.
resolves #515 
resolves #525
=> Feat/fix makers monument#515

Tree/Interface/Hud/Chat/Chat.gd
=> Fix Chat resize border detection

SceneComponent/Display/ViewportViewer.tscn, SceneComponent/Interface/Hud/CrosshairRayCast.gd, SceneComponent/Interface/Hud/HudCrosshair.gd, SceneComponent/Interface/Hud/HudCrosshair.tscn, Script/Manager/SignalsManager/HudSignals.gd, project.godot
- Add first person clickable layer for 3D Physics
resolves #541
=> HudCrosshair has click possible animation

SceneComponent/Interface/Hud/CrosshairRayCast.gd, SceneComponent/Interface/Hud/HudCrosshair.tscn
=> First person mode makes clickables emit mouse_entered or mouse_exited

Tree/Interface/Hud/Chat/Chat.tscn
=> Chat says to press ctrl+h for help display

SceneComponent/Actor/Humanoid/HumanoidMovement.gd
=> Feat/fix vertical stairs#552

Tree/Interface/Nametag/Nametag3D.gd, Tree/Interface/Nametag/Nametag3D.tscn
=> Fix nametag occlusion bug #520

SceneComponent/Utilities/VerticalStairs/VerticalStairs.tscn
=> Vertical Stairs title and description

Tree/Interface/UserSettings/UserSettings.gd, Tree/Interface/UserSettings/UserSettings.tscn, Tree/addons/HuePicker/HuePicker.gd
=> Make HuePicker bigger

SceneComponent/Actor/Debug/HumanoidMovementDebug.gd, SceneComponent/Actor/Debug/HumanoidMovementDebug.tscn, SceneComponent/Actor/Humanoid/HumanoidMovement.gd, Tree/Actor/Player/HumanPlayer.tscn, Tree/Actor/Vehicle/AthleteRover/AthleteRover.tscn
- Give control to the physics engine when the character is in the air
- Add physics material to characters
- Improve debugging tools
=> Improve humanoid air movement

Assets/Interface/Hud/Styles/HUDGeneralInfo.tres, Assets/Interface/Hud/Styles/HUDTheme.tres, Assets/Interface/Hud/Styles/ToolsBarTheme.tres, Assets/Interface/StyleBoxes/MoonwardsButtonDisabled.tres, Assets/Interface/StyleBoxes/MoonwardsButtonFocus.tres, Assets/Interface/StyleBoxes/MoonwardsButtonHover.tres, Assets/Interface/StyleBoxes/MoonwardsButtonNormal.tres, Assets/Interface/StyleBoxes/MoonwardsButtonPressed.tres, Assets/Interface/StyleBoxes/MoonwardsPanel.tres, Assets/Interface/StyleBoxes/MoonwardsTabBg.tres, Assets/Interface/StyleBoxes/MoonwardsTabDisabled.tres, Assets/Interface/StyleBoxes/MoonwardsTabFg.tres, Assets/Interface/StyleBoxes/MoonwardsVScrollBar.tres, Assets/Interface/StyleBoxes/MoonwardsVScrollBarGrabber.tres, Assets/Interface/StyleBoxes/MoonwardsVScrollBarGrabberHighlighted.tres, Assets/Interface/StyleBoxes/MoonwardsVScrollBarGrabberPressed.tres, SceneComponent/Interface/Hud/Apps/NPC/NPCApp.gd, SceneComponent/Interface/Hud/Apps/NPC/NPCApp.tscn, SceneComponent/Interface/Hud/Apps/ToolsBar/ToolsBar.tscn, SceneComponent/Interface/Hud/Apps/ToolsBar/ToolsBarRoot.gd, Tree/Interface/Hud/AppsContainer.gd, Tree/Interface/Hud/Hud.tscn, addons/joyeux_npc_editor/src/interface/States/Interface/States.tscn, addons/joyeux_npc_editor/src/interface/behaviors/code/Behaviour_tree_editor.tscn
=> NPC Editor moved to Hud #580 #579

SceneComponent/Interface/Hud/Radial/ButtonRow.gd, SceneComponent/Interface/Hud/Radial/RadialSelector.gd, SceneComponent/Interface/Hud/Radial/RadialSelector.tscn, SceneComponent/Interface/Hud/Radial/RowContainer.gd, Script/Manager/Helpers.gd, Script/Manager/HudManager/HudManager.gd, Script/Manager/SignalsManager/HudSignals.gd, Tree/Interface/Hud/AppsContainer.gd, Tree/Interface/Hud/Hud.gd, project.godot
Please let me know if the radial menu is to your liking please. Bring the menu up by going to Hud and middle clicking with the mouse. 
Do I need to hide the Hud menus when RadialMenu is present?
resolves #570
=> Radial Menu and expressions #570

project.godot
Just adds one action to project.godot Input Map.
=> RadialMenu action added back into project.godot

SceneComponent/Actor/InteractorComponent.gd, SceneComponent/Actor/InteractorComponent.tscn, SceneComponent/Actor/InteractorRayCast.gd, SceneComponent/Interface/Hud/InteractsMenu.gd, Script/GameLogic/Interact/Interactor/InteractorArea.gd, Tree/Actor/Vehicle/AthleteRover/AthleteRover.tscn, project.godot
=> Interactor Component as RayCast or Area #626

Assets/MoonTown/Constructs/First_Gallery/First_Gallery_Upper.glb, SceneComponent/Display/Tooltip/TooltipButton.tscn, Tree/World/Moon_Town_Main.tscn, project.godot
Text is written on tooltips for the Vertical Stairs, general construction, support columns, the Carousel, and the Light Tubes.
Still to be added, the heat exchangers the ramps, and the foundation floor. Coordinates will be listed below.
=> Set up tooltips in First Gallery Upper

SceneComponent/Actor/InteractorComponent.gd, SceneComponent/Interface/Hud/InteractsMenu.gd
Easy fix. Only changes InteractorComponent.gd
resolves #635
=> Fix Rover dismount #635

Assets/Interface/Hud/Styles/Apps/HUDApps.tres, SceneComponent/Interface/Hud/Apps/Building/BuildingApp.gd, SceneComponent/Interface/Hud/Apps/Building/BuildingApp.tscn, SceneComponent/Interface/Hud/Apps/ToolsBar/ToolsBar.tscn, SceneComponent/Interface/Hud/Apps/ToolsBar/ToolsBarRoot.gd
=> Add building app to Hud #571

SceneComponent/Actor/Humanoid/HumanoidMovement.gd
Hit the spacebar whilst on vertical stairs.
Resolves #649
=> Add input for dismounting vertical stairs 

SceneComponent/World/DynamicLoading/DynamicVisibilityTrigger.gd, SceneComponent/World/DynamicLoading/ReversingVisibilityTrigger.gd, Script/Manager/VisualTriggerManager/VisibilityManager.gd, Script/Threading/ThreadWorker.gd, project.godot
=> Add threaded & pseudo-async LOD management

Assets/MoonTown/Models/Neighborhood/Neighborhood-1.glb, Assets/MoonTown/Models/Neighborhood/Neighborhood-1.tscn
=> Move major cable to not intersect with vertical stairs

SceneComponent/Actor/CameraController.gd
=> Fix camera flight bar appearing outside flight #652

Assets/Interface/Fonts/TooltipDisplay.tres, Assets/Interface/Fonts/TooltipDisplay/TooltipDisplayBold.tres, Assets/Interface/Fonts/TooltipDisplay/TooltipDisplayBoldItalics.tres, Assets/Interface/Fonts/TooltipDisplay/TooltipDisplayItalics.tres, Assets/Interface/Fonts/TooltipDisplay/TooltipDisplayMono.tres, Assets/Interface/Fonts/TooltipDisplay/TooltipDisplayNormal.tres, Assets/Interface/Fonts/TooltipDisplayButton.tres, Assets/Interface/TooltipDisplay.tres, SceneComponent/Interface/Hud/TooltipDisplay.gd, SceneComponent/Interface/Hud/TooltipDisplay.tscn
=> Tooltip text indent #645

SceneComponent/Interface/AvatarPreview/AvatarPreview.tscn, Tree/Interface/UserSettings/UserSettings.tscn
=> Darken Avatar background  #678

SceneComponent/Actor/InteractorRayCast.gd, SceneComponent/Interface/Hud/HudCrosshair.gd, SceneComponent/Interface/Hud/HudCrosshair.tscn, Script/Manager/SignalsManager/HudSignals.gd
=> Animate Crosshair for Interactables #676

SceneComponent/Interface/CustomControls/CustomControls.tscn, Script/Manager/Helpers.gd, project.godot
=> Add customizeable actions #673

SceneComponent/Actor/InteractorComponent.gd, SceneComponent/Utilities/VerticalStairs/VerticalStairs.gd, Script/GameLogic/Interact/Interactable/Interactable.gd
=> Interacts networked system refactor

addons/joyeux_npc_editor/src/Core/Nodes.gd, addons/joyeux_npc_editor/src/interface/Settings/code/ItemList.gd
an oversight from the previous recursion fix, that brought the recursion issue back if the settings were changed, found it when working on the addon only version
=> fix config file growing each time its saved

SceneComponent/Actor/CameraController.gd
I was getting tired of the mouse moving the active when you were try to click on things.
resolves #700
=> Camera no longer responds to active mouse

SceneComponent/Actor/CameraController.gd
=> Walls don't push cameras toward butts #694

Assets/MoonTown/Constructs/First_Gallery/First_Gallery_Upper.glb, Assets/MoonTown/Constructs/First_Gallery/First_Gallery_Upper.tscn, Assets/MoonTown/Models/Neighborhood/Neighborhood-1.glb, Assets/MoonTown/Models/Neighborhood/Neighborhood-1.tscn, Assets/MoonTown/Models/Neighborhood/Shared-Facilities-1.tscn
The lights now use a mix of spot and omni lights, in a mesh setup that has broken up large objects into smaller pieces so that fewer lights affect each one. 
The light looks a lot better and the issue of lights turning on and off as the camera moves is almost gone. (There is one remaining wall object with this problem and I can't figure out why it's happening. It isn't the number of lights.)
I was not able to repair problems with GI probes and finally deleted them as they weren't doing anything. Lights have also been moved from MTM into FGU.
This should be ready to merge.
=> Set up new lighting system in First Gallery Upper

SceneComponent/Display/RocketDisplay.gd, SceneComponent/Display/RocketDisplay.tscn, SceneComponent/Display/RocketDisplay/RocketTheme.tres, Script/Manager/SceneManager/SceneManager.gd
=> Fix rocket display#698

Assets/Interface/Hud/Styles/HelpMenuPanel.tres, Assets/Interface/Textures/HudPanelMenu.png, Assets/Interface/Textures/HudPanelMenu.png.import, Assets/Interface/Textures/LeftArrowButtonPressed.png, Assets/Interface/Textures/LeftArrowButtonPressed.png.import, Assets/Interface/Textures/LeftArrowHover.png, Assets/Interface/Textures/LeftArrowHover.png.import, Assets/Interface/Textures/LeftArrowNormal.png, Assets/Interface/Textures/LeftArrowNormal.png.import, SceneComponent/Actor/Debug/HumanoidMovementDebug.tscn, SceneComponent/Interface/HelpMenu/GotoApps.gd, SceneComponent/Interface/HelpMenu/HelpMenu.gd, SceneComponent/Interface/HelpMenu/HelpMenu.tscn, SceneComponent/Interface/HelpMenu/InitialMenu.gd, SceneComponent/Interface/HelpMenu/Keys.gd, SceneComponent/Interface/Hud/Apps/ToolsBar/HelpButton.gd, SceneComponent/Interface/Hud/Apps/ToolsBar/PanelPopup.gd, SceneComponent/Interface/Hud/Apps/ToolsBar/ToolsBar.tscn, SceneComponent/Interface/Hud/GeneralInfo/GeneralInfo.gd, SceneComponent/Interface/Hud/GeneralInfo/GeneralInfo.tscn, SceneComponent/Interface/Hud/GeneralInfo/HelpPanel.gd, SceneComponent/Interface/Hud/GeneralInfo/MenuButtons.gd, SceneComponent/Interface/Hud/GeneralInfo/Panel.gd, SceneComponent/Interface/Hud/GeneralInfo/Quit.gd, SceneComponent/Interface/PlayerHud.tscn, Script/Manager/Helpers.gd, Tree/Interface/Hud/AppsContainer.gd, Tree/Interface/Hud/Hud.tscn, project.godot
resolves #587 , resolves #696 , resolves #586
=> Help and menu options in Hud #587

Assets/Interface/Fonts/TooltipDisplay.tres, Assets/Interface/Fonts/TooltipDisplay/TooltipDisplayBold.tres, Assets/Interface/Fonts/TooltipDisplay/TooltipDisplayBoldItalics.tres, Assets/Interface/Fonts/TooltipDisplay/TooltipDisplayItalics.tres, Assets/Interface/Fonts/TooltipDisplay/TooltipDisplayMono.tres, Assets/Interface/Fonts/TooltipDisplay/TooltipDisplayNormal.tres, Assets/Interface/Fonts/TooltipDisplayButton.tres, Assets/Interface/TooltipDisplay.tres, SceneComponent/Interface/Hud/TooltipDisplay.gd, SceneComponent/Interface/Hud/TooltipDisplay.tscn
=> Tooltip Display smaller #645

Assets/Interface/Textures/MoonwardsLogo2020-1200.png, Assets/Interface/Textures/MoonwardsLogo2020-1200.png.import, Assets/Interface/Textures/MoonwardsLogo2020_HeavyOutline_500px.png, Tree/Interface/MainMenu/MainMenu.tscn, icon.png
=> Update Moonwards Logo #711

SceneComponent/Interface/Hud/GeneralInfo/GeneralInfo.tscn
I checked that all the relevant menus are still working.
resolves #734
=> Fix help and menu panels blocking mouse clicks

SceneComponent/Interface/Hud/Apps/Building/BuildingApp.gd, SceneComponent/Interface/Hud/Apps/Building/BuildingApp.tscn
=> Building App buttons larger #603

SceneComponent/Object/Airlock/Airlock.tscn, SceneComponent/Object/Airlock/AirlockDoorInteractable.gd, SceneComponent/Object/PassengerPod/PassengerPodDockInteractable.gd
=> Fix pod docking vertically to open airlock doors

SceneComponent/Interface/Hud/Apps/ToolsBar/Button_Expand.gd, SceneComponent/Interface/Hud/Apps/ToolsBar/ToolsBar.tscn, SceneComponent/Interface/LoggerConsole/LoggerConsole.tscn, Script/Manager/SceneManager/SceneManager.gd
=> Player start UX improvement #736

SceneComponent/Actor/CameraController.gd
=> First person has better camera movement #573

project.godot
=> Fix space bar pressing buttons that you have clicked on previously. #715

SceneComponent/Interface/Hud/Apps/ToolsBar/ToolsBar.tscn, SceneComponent/Interface/Hud/GeneralInfo/GeneralInfo.tscn, Tree/Interface/Hud/Hud.tscn
=> Smaller hud #751

SceneComponent/Interface/Hud/Apps/ToolsBar/ToolsBar.tscn
=> Close button clickable #765

Assets/MoonTown/Constructs/South_Farm_Atrium/South_Farm_Atrium.tscn, Assets/MoonTown/Constructs/Teacup_Crater/Teacup_Crater.tscn
Added a few omni lights to these constructs. No other changes.
=> Add lights to South Atrium and Teacup Crater

SceneComponent/Actor/Humanoid/AnimationController.gd, SceneComponent/Actor/Humanoid/HumanoidMovement.gd, Script/Entity/ActorEntity.gd
=> Imrpove vertical stairs #737

Assets/MoonTown/Constructs/STEMP_Facilities/STEMP_Facilities.glb
=> Remove collision barrier around facilities, no longer needed

Assets/MoonTown/Constructs/First_Atrium/First_Atrium.glb, Assets/MoonTown/Constructs/First_Atrium/First_Atrium.tscn, Assets/MoonTown/Constructs/First_Gallery/First_Gallery_Upper.glb, Assets/MoonTown/Constructs/First_Gallery/First_Gallery_Upper.tscn, Assets/MoonTown/Models/Neighborhood/Neighborhood-1.glb, Assets/MoonTown/Models/Neighborhood/Shared-Facilities-1.glb
* remove vertical stairs in First Atrium so that procedural coded ones only are used
* fix top floors of main atrium stairs
* replace missing atrium columns
* fix FGU floor collision shape
* refine collision shape of Shared Facility stairs
* fix name of Neighborhood LOD0 node so it doesn't have suffix
Closes #748 #749
=> A set of repairs to First Atrium, Shared Facilities, Neighborhood, and FGU

SceneComponent/Display/RocketDisplay.gd, SceneComponent/Display/RocketDisplay.tscn, SceneComponent/Display/RocketDisplay/RocketTheme.tres
=> Fixed the camera position of the first stage of the rocket display.

SceneComponent/Interface/Hud/ChatComponent.tscn, Tree/Interface/Hud/Hud.tscn
=> ChatComponent added to Hud #739

SceneComponent/Object/Airlock/Airlock.tscn, SceneComponent/Object/Airlock/AirlockDoorInteractable.gd, SceneComponent/Object/PassengerPod/PassengerPodDockInteractable.gd
=> Add airlock simulation when docking pods

SceneComponent/Interface/Hud/HudCrosshair.gd, Script/Manager/Helpers.gd
=> First person crosshair visible. Radial Menu bug gone #783

SceneComponent/Actor/CameraController.gd, SceneComponent/Actor/Humanoid/HumanoidInput.gd, SceneComponent/Actor/InteractorComponent.gd, SceneComponent/Actor/Vehicle/AthleteRover/RoverInput.gd, SceneComponent/Actor/Vehicle/AthleteRover/RoverInput.tscn, Script/Manager/InputManager/MwInputManager.gd, Script/Manager/InputManager/MwInputManager.tscn, project.godot
=> Fix chat input overlap

SceneComponent/Interface/LoggerConsole/LoggerConsole.gd, SceneComponent/Interface/LoggerConsole/LoggerConsole.tscn, SceneComponent/Interface/LoggerConsole/LoggerText.gd
=> Logger Console fixed #805

SceneComponent/Interface/Hud/InteractsMenu.tscn
=> Right side Interacts Menu #789

Main.gd, SceneComponent/Actor/Humanoid/HumanoidMovement.gd, Script/Entity/ActorEntity.gd, Script/Entity/VehicleEntity.gd, Tree/Actor/Player/HumanPlayer.tscn, project.godot
Couple more network optimizations.
Resolves #821
=> Player animation will no longer hitch on missed packets

SceneComponent/Actor/InteractorComponent.gd
=> Fix left click release Interaction bug #830

SceneComponent/Interface/HelpMenu/HelpMenu.tscn, SceneComponent/Interface/Hud/GeneralInfo/HelpPanel.gd
=> Add close button to Help Menu #815

SceneComponent/World/DynamicLoading/DynamicVisibilityTrigger.tscn, SceneComponent/World/DynamicLoading/ReversingVisibilityTrigger.tscn
I moved Visibility trigger and reverse vts collisions to Player layer.
resolves #835
=> Fix Airlock Interactable click #835

SceneComponent/Actor/Debug/HumanoidMovementDebug.gd, SceneComponent/Actor/Humanoid/HumanoidMovement.gd
=> Stop human flight from activating while chatting #849

SceneComponent/Actor/CameraController.gd, SceneComponent/Actor/Humanoid/HumanoidInput.gd, SceneComponent/Actor/Vehicle/AthleteRover/RoverInput.gd, Script/Manager/SignalsManager/EntitySignals.gd, Tree/Actor/Player/HumanPlayer.tscn, Tree/Actor/Vehicle/AthleteRover/AthleteRover.tscn
We need to refactor how cameras work. Right now they are all processing at the same time.
The way components work are the main reason that happens.
resolves #693
=> Player and rover do not move while camera flying #693

Assets/Displays/ExclamationMark.png, Assets/Displays/ExclamationMark.png.import, SceneComponent/Actor/AnchorMovement.gd, SceneComponent/Actor/AnchorMovement.tscn, SceneComponent/Object/PassengerPod/PodAnchorMovementInteractable.gd
=> Grabbing pole has visuals #829

SceneComponent/Actor/InteractorComponent.gd, SceneComponent/Interface/Hud/InteractDisplay/InteractDisplay.gd
=> Update Interacts Display text #813

SceneComponent/Object/PassengerPod/RoverRideRelayInteractable.tscn
Rover relay does not network. Do you need me to test that client to client works? I only tested it by having a server with one client.
resolves #845
=> Fix Rover relay networking #845

SceneComponent/Audio/AudioSphere/AudioSphere.tscn, Script/GameLogic/Interact/Interactable/Interactable.gd
=> Don't network Audio Spheres #846

SceneComponent/Interface/Hud/InteractsMenu.gd, SceneComponent/Interface/Hud/InteractsMenu.tscn
=> Fix the Rover crash #856

SceneComponent/Actor/InteractorComponent.gd, SceneComponent/Actor/InteractorComponent.tscn, SceneComponent/Utilities/VerticalStairs/VerticalStairs.tscn
=> Add max distance to interactables

addons/joyeux_dialog_system/src/components/display/Dialog Display.tscn
=> set the dialog display to resize, avoid blocking UI elements

SceneComponent/Interface/CustomControls/CustomControls.gd, SceneComponent/Interface/CustomControls/CustomControls.tscn, SceneComponent/Interface/Hud/GeneralInfo/GeneralInfo.tscn, SceneComponent/Interface/Hud/GeneralInfo/MenuButtons.gd, SceneComponent/Interface/Hud/GeneralInfo/Panel.gd, SceneComponent/Interface/MenuPanel/MenuPanel.tscn
=> Add Custom Controls to Menu Panel #823

Assets/MoonTown/Constructs/Rec_Hab_1/Rec_Hab_1.tscn
=> Align stairs in rec hab #887

SceneComponent/Object/PassengerPod/PodAnchorMovementInteractable.gd
=> Anchor movement poles do not allow vehicles

SceneComponent/Actor/InteractorComponent.gd
=> First person reticule can scroll text boxes #826

SceneComponent/Actor/Humanoid/HumanoidMovement.gd
=> Mounting top of vertical stairs has you start further down #753

Tree/Object/PassengerPod/PassengerPod.tscn
=> Add display info to Rover Relay #874

SceneComponent/Actor/AI/NPCMovement.gd
making it by distance failed horribly when they jump, so recalculation should be timed only
=> recalculate npc path each 3 seconds if point in path hasn't been reached

Tree/Interface/MainMenu/MainMenu.tscn
=> Main Menu app section label wordings#862

Assets/Interface/Fonts/MainMenu_Header_Roboto.tres, SceneComponent/Interface/MainMenu/Destination.gd, SceneComponent/Interface/MainMenu/Destination.tscn, Tree/Interface/MainMenu/MainMenu.tscn
=> Main Menu wording improved #911

SceneComponent/Actor/CameraController.gd, Script/Manager/Helpers.gd, Script/Manager/SceneManager/SceneManager.gd
=> Mouse starts active when game world is loaded #894

SceneComponent/Actor/AI/Workstation.tscn, SceneComponent/Object/PassengerPod/PodAnchorMovementInteractable.tscn
=> Update Pole and NPC interact display info #899

Tree/World/Moon_Town_Main.tscn
=> Move spawn point to Maker's Monument #912

Tree/Interface/MainMenu/Links.gd, Tree/Interface/MainMenu/MainMenu.tscn
=> Add social media links to Main Menu #921

SceneComponent/Actor/Humanoid/HumanoidMovement.gd
=> Disable collisions when climbing stairs #924

SceneComponent/Object/PassengerPod/RoverRideRelayInteractable.gd
No issue has been created yet. I made  Rover detection have better logic for handling multiple Rovers running around it. Hopefully this fixes the issue of the relay not appearing.
=> Fix Rover relay bugs

SceneComponent/Object/PassengerPod/PassengerPodHatchInteractable.tscn
=> Hatch networked between clients #934

SceneComponent/Actor/Humanoid/HumanoidMovement.gd
Fixes a crash when climbing Vertical Stairs of different sizes on public servers.
=> Fix VerticalStairs crash

SceneComponent/Interface/BackgroundCycler/Background.gd, SceneComponent/Interface/BackgroundCycler/BackgroundCycler.tscn
=> Maint/background cycles#950

SceneComponent/Interface/Hud/Chat/ChatDisplay.gd, SceneComponent/Interface/Notifications/PopupNotice.gd, SceneComponent/Interface/Notifications/PopupNotice.tscn, Script/Manager/Helpers/Helpers.gd
PopupNotices and Chat can have multiple links
=> Multi link messages do not crash the game

SceneComponent/Actor/CameraController.gd
=> Camera Controller updates when chat is active #959

SceneComponent/Actor/InteractorComponent.gd, Script/Manager/Helpers/Helpers.gd, _tests/Display/BaseDisplayTest.tscn
=> Improve Interactor Component using Clickables

SceneComponent/Interface/TutorialMenu/TextFormatter.gd, SceneComponent/Interface/TutorialMenu/TutorialMenu.gd, SceneComponent/Interface/TutorialMenu/TutorialMenu.tscn
=> Tutorial menu pops up unless set not to #933

SceneComponent/Actor/InteractorComponent.gd, SceneComponent/Object/PassengerPod/PassengerPodDockInteractable.gd, SceneComponent/Object/PassengerPod/PassengerPodDockInteractable.tscn
=> Passenger Pod text is improved #967

SceneComponent/Actor/InteractorComponent.gd
I made it where the server will check that the interactable and arguments passed is valid before working on them in request_interact
resolves #973
=> Check for invalid Interactables being passed

Tree/Actor/Vehicle/AthleteRover/AthleteRover.tscn
This should make using Outdoor Audio Spheres easier.
=> Increase Rover Interactor cast range

SceneComponent/Object/PassengerPod/PassengerPodDockInteractable.gd, Script/Network/NetworkManager/NetworkManager.gd
@Reousa I tested on a local network and everything seems to be working just fine.
resolves #979
=> Fix pod crashing on servers #979

SceneComponent/Display/RocketDisplay.gd, SceneComponent/Display/RocketDisplay.tscn
=> Adjust Rocket Display UI positioning

SceneComponent/Display/RocketDisplay.gd, SceneComponent/Display/RocketDisplay.tscn
Also fixed the FOV not being the same as the user camera.
And made the interaction collision surround the rocket so that it can be clicked.
Transition animations still work and the user can still rotate the view around the rocket by clicking and dragging.
=> Made rocket display use the same UI layout as the Tooltips.

SceneComponent/Interface/Hud/Chat/Chat.tscn
=> Chat input clickable by mouse to prevent soft lock

SceneComponent/Display/Billboard/Billboard.gd, SceneComponent/Display/Billboard/Billboard.tscn, SceneComponent/Display/Billboard/Slide2DControl.gd, SceneComponent/Display/Billboard/Slide2DControl.tscn
=> Slide Presentation/Billboards is now networked #996

Assets/Characters/Phill.jsm, Assets/Characters/Steve.jsm, Assets/Dialogs/Help_me.mtalk, Assets/Dialogs/following.mtalk, Assets/Dialogs/thanks.mtalk, SceneComponent/Actor/AI/NPCMovement.gd, SceneComponent/Actor/AI/Workstation.gd, Tree/Actor/Player/NPC.tscn, Tree/World/Moon_Town_Main.tscn, addons/joyeux_dialog_system/src/components/display/Dialog Display.gd, addons/joyeux_npc_editor/Config/Definitions.gd, addons/joyeux_npc_editor/src/Core/Nodes.gd, addons/joyeux_npc_editor/src/NPCs/DefaultBehaviors/answer_for_help.jbt, addons/joyeux_npc_editor/src/NPCs/DefaultBehaviors/ask_for_help.jbt, addons/joyeux_npc_editor/src/NPCs/MwNPC.gd, addons/joyeux_npc_editor/src/NPCs/NPC.gd, addons/joyeux_npc_editor/src/interface/behaviors/scenes/Graph_compiler.gd
Steve asks the players to guide him to the pool. He will follow players and stop when either a player tells him to, or when the pool has been reached. 
Steve serves as a stress test for the NPC system in general, and this PR includes multiple fixes and features:
- Fixed a connection issue that avoided correct change of states. 
- Fixed a connection issue that avided correct disconection of signals, causing a crash. 
- Fixed an issue where a dialog wouldn't free correctly.
- Added conditionals. 
- Added a signal that's emited when a dialog finishes, passing the last dialog title. 
- Added functionality to get and set variables from a behavior tree. 
- Added a destinations system for NPC quests inside Workstations. 
This PR is currently on hold, until navigation mesh and NPC steering …
=> Steve: Quest-like character

SceneComponent/Interface/Hud/Chat/Chat.tscn, SceneComponent/Interface/Hud/ChatComponent.gd
@Moonwards  Time to live feature should be working. Just check that the messages are saved between sessions.
You need one server on play private game and someone to connect via join private game to see the message carry over.
resolves #1003
=> Feat/chat history sync#1003

Tree/Actor/Player/Android.tscn
=> Fix Android getting caught dismounting stairs #1023

SceneComponent/Display/MakersMonument/MonumentContent.gd
=> Make Maker's Monument audio a soloist #976

Assets/MoonTown/Constructs/First_Gallery/First_Gallery_Upper.tscn
Just adds an Animation Player to the Carousel so it spins continuously at the right rate for 1 g.
=> Animate Carousel to spin for artificial gravity

Script/GameLogic/Detect/Detector/Detector.gd
=> Detector listens for the correct exited signal #1032

SceneComponent/Object/PassengerPod/PodAnchorMovementInteractable.gd, Script/Component/Core/AComponent.gd, Script/Entity/ActorEntity.gd, Script/Entity/VehicleEntity.gd, Script/ExtensionClass/MwSpatial.gd, Script/Network/NetworkManager/ANetworkInstance.gd, Script/Network/NetworkManager/NetworkManager.gd
resolves #1030
@Reousa Tagging you because you are the networking guru.
=> Maint/networking congestion#1030

Assets/MoonTown/Constructs/Main_Factory/Main_Factory.glb, Assets/MoonTown/Constructs/Main_Factory/Main_Factory.tscn, Assets/MoonTown/Models/Android/Android-Prop.glb.import, Assets/MoonTown/Models/Android_Control_Kiosk/android_kiosk_simple_row.glb.import, Assets/MoonTown/Models/Spacesuit/Spacesuit.glb.import
resolves #1051 
@Moonwards I just set the rotation of Main_Factory's Android Depot's parent to zero.
=> Unrotate Main_Factory android depot #1051

project.godot
resolves #1045 
Super minor change to remove an annoying error
=> Change shift action to Shift #1045

SceneComponent/Interface/GraphicsSettings/GraphicsOptions.gd, SceneComponent/Interface/GraphicsSettings/GraphicsSettings.gd, SceneComponent/Interface/GraphicsSettings/GraphicsSettings.tscn
=> Add graphics settings #1028

SceneComponent/Actor/Humanoid/HumanoidInput.gd, SceneComponent/Actor/Humanoid/HumanoidMovement.gd, SceneComponent/Actor/InputEPI.gd, SceneComponent/Actor/InputEPI.tscn, Script/Component/Core/AComponent.gd, Script/Component/Core/EPIBase.gd, Script/Entity/Core/AEntity.gd, Script/Manager/EPIManager/EPIManager.gd, Script/Manager/EPIManager/EPIManager.tscn, Script/Manager/SceneManager/SceneManager.gd, Tree/Actor/Player/Android.tscn, Tree/Actor/Player/HumanPlayer.tscn, Tree/Actor/Player/NPC.tscn, Tree/Actor/Player/Spacesuit.tscn, Tree/Actor/Vehicle/AthleteRover/AthleteRover.tscn, project.godot
This PR showcases the beginning of the EPI system and updates humanoid input to use it.
=> Starting refactor of AEntities and input system
